brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "git"
brew "gh"
brew "git-secrets"
brew "tree"
brew "wget"
brew "uv"

cask "slack"
cask "visual-studio-code"
cask "notion"
cask "raycast"